baseURL: "http://paoloandrea.it"
#relativeURLs: true
languageCode: "it"
title: "Andrea Paolo"
theme: hugo-profile
pluralizelisttitles: "false"

Paginate: 6
googleAnalytics: G-V6BN6K1NRS
enableRobotsTXT: true
enableGitInfo: true
canonifyUrls: true

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    #Dropdown menu
    - identifier: dropdown
      title: Dropdown
      name: Articoli
      weight: 2

    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      parent: dropdown
      weight: 1

    - identifier: tips
      name: Tips della Domenica
      title: "Tips"
      url: /tips
      parent: dropdown
      weight: 1
      
    - identifier: schede
      title: Schede
      name: Allenati con me
      url: /schede
      parent: dropdown
      weight: 2

params:
  title: "Andrea Paolo"
  description: Istruttore e Personal trainer di Firenze
  keywords: "Andrea,Paolo,istruttore,personal trainer,firenze,palestra,fitness,allenamento,online coaching,coaching"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"
  #customCSS: true

  theme:
    disableThemeToggle: false

  font:
    #fontSize: 1.5rem # default: 1rem
    fontWeight: 500 # default: 400
    #lineHeight: 1 # default: 1.5
    #textAlign: right # default: left

  menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
    disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Ciao, sono"
    title: "Andrea Paolo."
    subtitle: "Istruttore e Personal trainer"
    content: "Appassoniato del fitness e della cultura fisica, il mio lavoro è farti arrivare alla condizione fisica che hai sempre voluto avere!"
    image: /images/profilo.jpg
    button:
      enable: true
      name: "Contattami"
      url: "#contact"
      download: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-instagram
          url: https://www.instagram.com/andrea_paolo_/
        - icon: fab fa-facebook
          url: https://www.facebook.com/Coach-Andrea-Paolo-105673301165577
      customIcons:
        - icon: /favicon.ico
          url: https://linktree.paoloandrea.it/

  # About
  about:
    enable: true
    title: "Su di me"
    image: "/images/me.jpg"
    content: |-
      Lo sport è sempre stato al centro della mia vita, fin da bambino mi ha sempre affascinato il mondo del movimento.
      Ho iniziato a praticare sport fin dai primi anni di vita con il nuoto, successivamente sono passato alle arti marziali ed infine alla pallavolo. Solo in età post adolescenziale mi sono avvicinato al mondo del fitness e alla sala pesi.

      Oggi sono istruttore e personal trainer certificato Coni, il mio obiettivo è quello di far raggiungere la codizione fisica che avete sempre sognato; ma soprattutto fare informazioni su tutto ciò che riguarda il mondo del fitness.
    skills:
      enable: true
      title: "Tutti i titoli da me conseguiti:"
      items:
        - "Istruttore sala pesi"
        - "Personal trainer"
        - "Preparatore atletico"
        - "Istruttore funzionale"
        - "Istruttore senior"
        - "Istruttore junior"

  # Experience
  experience:
    title: "Esperienze"
    enable: true
    items:
      - job: "Personal trainer"
        company: "Palestra TimeOut"
        companyUrl: "https://palestratimeout.com"
        date: "Ottobre 2018 - oggi"
        info:
          enable: true
          content: Personal trainer in presenza che online
        content: "Da ottobre 2018 ad oggi mi occupo di personal training uno ad uno o uno a più persone, sia in presenza che online. "

      - job: "Istruttore di salal"
        company: "Palestra TimeOut"
        companyUrl: "https://palestratimeout.com"
        date: "Agosto 2022 - oggi"
        info:
          enable: true
          content: Assistente di sala
        content: "Da agosto 2022 ad oggi lavoro come assite te di sala presso la palestra TimeOut. "

      - job: "Divulgatore"
        company: "Instagram"
        companyUrl: "https://www.instagram.com/andrea_paolo_/"
        date: "Maggio 2020 - Oggi"
        featuredLink:
          name: Instagram
          enable: true
          url: "https://www.instagram.com/andrea_paolo_/"
        info:
          enable: true
          content: Divulgatore fitness su instagram
        content: |
          Da maggio 2020 mi occupo di divulgazione sui social di tutto ciò che riguarda la salute ed il mondo del fitness. 

          Il mio obiettivo è quello di sfatare i falsi miti del fitness, non creare false aspettative sui risultati e soprattutto sviscerare i concetti difficili e renderli accessibili a tutti.
  
  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Diploma Personal Fitness Trainer"
        school:
          name: "AICS eps Coni"
          url: "https://www.aics.it/"
        date: "2019 - 2020"
        content:
       
      - title: "Laurea triennale Scienze Motorie L.22"
        school:
          name: "Università telematica Pegaso"
          url: "https://www.unipegaso.it/corsi-di-laurea/scienze-motorie"
        date: "2020 - 2023"
        GPA: ""
        content:

  # Achievements
  achievements:
    enable: true
    items:
      - title: Abxolute Nutrition
        content: Sponsor ufficiale Abxolute Nutrition, con il codice "AP10" avrete il 10% di sconto su tutto il sito
        url: https://www.abxolutenutrition.com/?sca_ref=462521.8k7XeO6Ljc
    
  #Contact
  contact:
    enable: true
    content: "Se hai delle domane, dei dubbi o semplicemente vuoi più informazioni non esitare a contattarmi."
    email: info@paoloandrea.it
    btnName: Contattami

  footer:
    # recentPosts: false
    socialNetworks:
      #github: https://github.com
      #linkedin: https://linkedin.com
      wabusiness: "https://api.whatsapp.com/send?phone=393516567574"
      instagram: https://www.instagram.com/andrea_paolo_/
      facebook: https://www.facebook.com/Coach-Andrea-Paolo-105673301165577
