version: '3'
services:
  hugo-app:
    image: jojomi/hugo:latest
    volumes:
      - "./:/src"
    restart: unless-stopped

  hugo-web:
    image: pagespeed/nginx-pagespeed
    volumes:
      - "./:usr/share/nginx/html:ro"
