version: '3'
services:
  hugo-app:
    image: citoyx/hugo
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:www.citoyx.com"
      - "traefik.port=1313"
      - "traefik.backend=hugo"
      - "traefik.frontend.entryPoints=http,https"
    volumes:
      - "/data/work/hugo:/srv/hugo"
    environment:
      - HUGO_BASEURL=https://www.citoyx.com
    ports:
      - "1313:1313"
    restart: unless-stopped
