version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: hugo-nginx
    restart: unless-stopped
#    ports:
#      - 8081:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`ap.ubuntu.local`)"
      - "traefik.http.routers.nginx.entrypoints=web, websecure"
#      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.nginx.tls=true"
      #- "traefik.http.routers.nginx.tls.certresolver=production"
    volumes:
      - ./:/var/www
      - ./docker-compose/:/etc/nginx/conf.d
#      - "./public:/var/www/html/public:ro"
#      - "./storage/app:/var/www/html/storage/app:ro"
    networks: 
      - lan
      
networks: 
  lan:
    external: true
